### ISSUE TITLE
camelCase versus underscore_case 

### ISSUE THREAD

**Issue by ubuntuslave** [raywenderlich/swift-style-guide#125]
Shouldn't the naming convention for functions and variables be left to the style of the programmer? Some prefer underscore_case over CamelCase. I can't tell you which one is clearer, but the style guide here should not enforce CamelCase for naming variables and functions.   However, Classes should use CamelCase always (as a convention across most languages).

**Comment by tristancelebi** [comment]
Since when is a styleGuide enforcing someone. I prefer camelCase too. At the end of the day it is up to you.

**Comment by msheaver** [comment]
Since this is a style guide, the intent is to put forth a set of best practices to improve the coding, debugging and maintaining of Swift code, Given that Apple and most developers use camelCase as the de facto standard, it should be camelCase here as well.

**Comment by micpringle** [comment]
@ubuntuslave 

Whilst this style guide is open for anyone to adopt or contribute to, it was originally set up to provide guidance to authors contributing to raywenderlich.com tutorials and books, so our code is consistent across everything we produce, regardless of who actually wrote it. This is for the benefit of our readers.

In this particular case we prefer our authors use CamelCase, which is why it's in the guide. :smile:
