### ISSUE TITLE
Enum cases

### ISSUE THREAD

**Issue by rayfix** [raywenderlich/swift-style-guide#174]
In Swift 3, enumerations and OptionSetType constants will import as lower camel case.  The standard library will also use lowerCamelCase for all enum cases.  The current RW guide instructs authors to use UpperCamelCase.  I think we are going to need to change this rule to better integrate with Apple's standard.

I see three options:

  1. leave the rule as is (for now)
  2. leave the rule as is but note that it will be changing in Swift 3
  3. proactively change the rule to lower camel case in anticipation of swift 3

**Comment by jawwad** [comment]
@rayfix - I feel that option 2 will be better for tutorials until Swift 3 is released. Readers who are not up to date with what changes will be in Swift 3 may think that we are using incorrect style or syntax. Also this might create a bit more work for the tech editors, since they would probably be the ones that would need to "correct" the enums in any projects to the newer style.

**Comment by rayfix** [comment]
@jawwad I talked through this issue with the RW team leads yesterday.  @micpringle made a strong case for 3 which is why I decided to move in that direction. There is another moving part to this as my update article talks specifically about this change.  Since Xcode isn't fighting against us here, are skating to where the puck is going.  It will make updates easier in the future.  cc/ @rwenderlich

**Comment by jawwad** [comment]
@rayfix - Ohhh @micpringle said it should be option 3. Why didn't you say so? Then of course option 3 is the correct one. :)
