### ISSUE TITLE
Member definition on the same line

### ISSUE THREAD

**Issue by kevinrandrup** [raywenderlich/swift-style-guide#176]
Classes and Structures -> Example Definition

    class Circle: Shape {
      var x: Int, y: Int
      ...

If they are being treated as a single entity why not use CGPoint or a tuple instead? 

"Common purpose/context" sounds like you would want a tuple.

**Comment by rayfix** [comment]
This example that has been around since the beginning of the Style guide.   I don't think the purpose is to show what the optimal design is for a `Shape.`  (I think you are right, having a center: CGPoint is probably better design for a shape!)  

I read it as being acceptable to put the same property on the same line when they are closely related.  

For example, 

```swift
struct FourierSample {
  var angle: Radians, magnitude: Decibels
}
```
But these are a little more esoteric.  I generally don't like creating tuples because it makes passing them around becomes too verbose and too easy to make inconsistent.

**Comment by grosch** [comment]
Your FourierSample example is VERY confusing.  I have to stare at it for a few moments to even figure out what it means.

**Comment by rayfix** [comment]
Yeah, sorry.  It was meant to be SobelSample or SobelPixel.  I am sure that makes it clear now. ;]  (There is a reason why that isn't in the actual guide. 😉 )

The point I was trying to make is have two variables that are closely related to one another such as x and y or angle and magnitude, it is okay to declare them on the same line.  There is a reason why Swift affords this kind of initialization pattern and I think it is okay to use it.
