### ISSUE TITLE
Preferred (zero based) variable / class abbreviations

### ISSUE THREAD

**Issue by johndpope** [raywenderlich/swift-style-guide#182]
class func create() -> KHHomeNavigationController {
        let homeViewController = HomeViewController(nibName: "HomeViewController", bundle: NSBundle.mainBundle())
        let homeNavCntrl = KHHomeNavigationController(rootViewController: homeViewController)
        homeNavCntrl.navigationBar.tintColor = UIColor.karhooPrimaryRed()
        homeNavCntrl.homeViewController = homeViewController
        return homeNavCntrl
    }

preferred

    class func create() -> KHHomeNavigationController {
        let homeVC = HomeViewController(nibName: "HomeViewController", bundle: NSBundle.mainBundle())
        let homeNC = KHHomeNavigationController(rootViewController: homeVC )
        homeNC.rootViewController = homeVC 
        return homeNC
    }

**Comment by konrado0905** [comment]
Could you add some description?

**Comment by rayfix** [comment]
Issues I see with the sample are:

1. The not preferred block and the preferred block don't do the same thing
2. KHHomeNavigationController should be HomeNavigationController

I agree that it is okay to use very short variable names when the scope is not more than a few lines, but I don't know if it is a style that should be legislated.  controller and navigation would seem okay too. Looking for more feedback on that.  vc seems like it is just an initialism of a name which is not preferred.

**Comment by JRG-Developer** [comment]
> I agree that it is okay to use very short variable names when the scope is not more than a few lines, but I don't know if it is a style that should be legislated.

I agree. Let's leave this to the discretion of the author and tech editor.

**Comment by johndpope** [comment]
Let's close this - but when you're reading someone else's code that's littered with inconsistent variable names - let this ticket come back to haunt you. 
& I hate to bust your bubble - but none of this guide is 'legislation'.

**Comment by rayfix** [comment]
I am happy to keep it open for a bit longer to get some more input / thoughts.  Names are important so I appreciate the sentiment!  The next update isn't until Fall so we have time to let these ideas marinate.

Sorry 'legislation' was probably not the right word choice.  The authors at RW are required to follow this guide so it does have some teeth (albeit in our small little micro-universe) :]

**Comment by JRG-Developer** [comment]
> I hate to bust your bubble - but none of this guide is 'legislation'

While this style guide is definitely useful in many contexts, it's main purpose is to ensure consistent style across RayWenderlich.com tutorials.

It's used by RW authors and tech editors to ensure '"correctness" in a sense-- how well tutorials conform to this style guide is one of the scales by which tutorials are "graded". In this regard, it _is_ a type of legislation.

**Comment by RobertGummesson** [comment]
I'd say it stretches outside of the RW universe, @rayfix . I have no association with RW but have worked on two separate companies where the RW guide (obj-c back then) was the company style guide with some smaller tweaks.

I personally prefer the same naming convention between all variables. In other words, I wouldn't do
`var b = UIButton()`
for the same reason I wouldn't do:
`@IBOutlet weak var b: UIButton!`

If the rule of thumb is that variable names can be short if the scope is a few lines, there is always the risk that more code is added later and those names are not refactored. It could also be a bit weird to have one naming convention for short methods and another for longer.

**Comment by johndpope** [comment]
WRT a single letter definition - consider this ....

var d = Dictionary()
var d2 = Dictionary() <- 2???

preferred
var d0 = Dictionary()
var d1 = Dictionary()

**Comment by rayfix** [comment]
I see @johndpope changed the title of this issue.  Type names are a different issue since they are generally more global in scope.  We are already following the Apple API Design Guidelines on that, which is not to use abbreviations such as VC for ViewControllers.  (You will find that you are fighting Xcode a little if you shorten to VC.  I know this from personal experience since I adopted the VC style naming in my first Obj-C project many years ago!  Tutorials don't want to be fighting Xcode.)

@RobertGummesson It is a very good point about refactoring and future proofing.  Still, I think a shorter variable in highly local scope is easier for my brain to parse (`b` is probably extreme though).  On the other hand a global variable needs to have a very explicit and is often long as a side-effect.  Maybe another reason why there shouldn't be a hard rule on it.

@johndpope Regarding single letters, your examples don't actually compile because they don't have enough type information.  I feel it is always better to use a name that reflects the role of the variable such as `priceLookup` as opposed to `d0` or something.

**Comment by RobertGummesson** [comment]
>  Maybe another reason why there shouldn't be a hard rule on it.

Very true. If my method did nothing more than configuring a button, I'd be ok with calling it `button` since the method name is likely descriptive enough.

If there are multiple buttons, I'd prefer:
`var closeButton = UIButton()`
`var refreshButton = UIButton()`
over:
`var b0 = UIButton()`
`var b1 = UIButton()`

I treat Outlets the same way. If I have subclassed UITableViewCell and have nothing more than a label in there, I may very well do:
@IBOutlet weak var label: UILabel!
until there are more outlets and it has to be refactored.

**Comment by hollance** [comment]
Just one person's opinion, I hate variable names like `btn`. I'm OK with calling something like an array `a` or `x` if the scope in which it is used is small and the variable is temporary. But if you're going to use more than one letter you might as well type the entire word. It's not more work to write `button` instead of `btn` and it's a lot clearer. That's not to say abbreviations never make sense, but you gain nothing by this particular one.

**Comment by jawwad** [comment]
@hollance 👍 👍 👍

**Comment by JRG-Developer** [comment]
Here are my thoughts:

To quote [Clean Code](http://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882),

> The length of a name should correspond to the size of its scope.

If a variable is limited to only a few lines (e.g. less than 10, method scope), I may be okay with a single letter name (if it's clear in context), and I'm usually okay with a generic name like `button`, `array`, etc.

For properties, methods, or anything else with a larger scope than this, I'm likely _not_ okay with any type of abbreviated name.

Consequently, I'm against a general rule such as, for example,

> You should abbreviate UIViewController instances as `vc`.

I think our current naming rules are actually pretty good:

They provide guidance

`Use descriptive names with camel case for classes, methods, variables, etc`

and

`Abbreviations and acronyms should generally be avoided.`

Yet they aren't stiflingly strict, either. For example, they _don't_ say "abbreviations shouldn't be used."

IMHO, I think this is a reasonable compromise, and I think they should be left as is.

**Comment by RobertGummesson** [comment]
Since this issue is still open, I thought I'd add what Apple had to say about this during WWDC (Swift API Design Guidelines). ...and I very much agree with it.

_"Resist the temptation to optimise for bad code. It is absolutely true that someone can go an use names like ‘a’, ‘b’ and ‘c’ for all the variables. This code is not clear anymore."_ 

**BAD:**
```
if let c = a.index(of: b) {
  a.remove(at: c)
}
```

**GOOD:**
```
if let completedPosition = tasks.index(of: completed) {
  tasks.remove(at: completedPosition)
}
```

**Comment by anatoliyv** [comment]
Absolutely agree with @RobertGummesson. More readable code leads to less mistakes and easy refactoring if required.
