### ISSUE TITLE
Closure expressions

### ISSUE THREAD

**Issue by anatoliyv** [raywenderlich/swift-style-guide#189]
I like how it looks like in your animation example [here](https://github.com/raywenderlich/swift-style-guide#closure-expressions), but there is a problem with this code block and XCode. Just try to copy-paste it and you will get something terrible:

<img width="545" alt="untitled-1" src="https://cloud.githubusercontent.com/assets/1595032/15357955/9f678e9c-1d0a-11e6-96f0-7a4ed96a9521.png">

It will take time to correct all this. 

From the other side if you format this like below XCode will pre-format it in much more suitable way (I prefers 4-space tabs) and it take less lines of code:

```
UIView.animateWithDuration(1.0, animations: {
        self.myView.alpha = 0
    }, completion: { finished in
        self.myView.removeFromSuperview()
    })
```

Copy-paste still looks a bit unformatted, but it's easier to correct it.

**Comment by rayfix** [comment]
A very astute observation.  👏

**Comment by jawwad** [comment]
I can provide some context on this (since I'm the one that originally proposed this format). It looks like this broke with a recent version of Xcode since I know for a fact that this was pretty much the only format that would indent properly. Now it looks like Xcode is just being weird again. 

By the way the proposed format doesn't "autoindent" properly in Xcode for me. When I paste it in Xcode I get the following:

        UIView.animateWithDuration(1.0, animations: {
            self.myView.alpha = 0
            }, completion: { finished in
                self.myView.removeFromSuperview()
        })

Maybe Xcode 8 will fix it?

**Comment by RobertGummesson** [comment]
It didn't. 🤔  At least not the beta version. I would vote to go with @anatoliyv's suggestion. That's also more consistent with Xcode's built-in code snippet for UIView animations.

**Comment by eranmarom** [comment]
Any suggestion regarding this issue?

**Comment by rayfix** [comment]
Although I updated the format for the particular example, I don't have a rule that describes it.  In practice it may be too difficult to enforce.
