### ISSUE TITLE
Rethinking the "mark classes final" recommendation for tutorials

### ISSUE THREAD

**Issue by jawwad** [raywenderlich/swift-style-guide#254]
@rayfix - The style guide [states](https://github.com/raywenderlich/swift-style-guide/blob/swift3/README.markdown#final) "Mark classes `final` when inheritance is not intended."

While this is good coding practice I feel hesitant for it to be made a formal recommendation for the following reasons:
- The first sentence in the [Access Control](https://github.com/raywenderlich/swift-style-guide/blob/swift3/README.markdown#access-control) section with regard to the `private` modifier states `Full access control annotation in tutorials can distract from the main topic and is not required." I think the same principle should apply here.
- In general, the majority of classes don't need to be subclassed, which would mean that this modifier would need to be used quite often. Making it a recommendation means that tech editors for articles on [RayWenderlich.com](RayWenderlich.com) and for [RWDevCon](https://www.rwdevcon.com/) would need to add this in if it was missing. In general, this isn't a commonly used modifier for a lot of swift developers and in fact, many may have never used it, so this would be left out by authors quite often. Also some Tech Editors may feel that this shouldn't be that strict of a rule so they may be ok with the author of the tutorial leaving it out, so this would lead to inconsistency. Even if it is ok for the tech editors to not enforce this rule, some authors will now start adding the `final` modifier since it is now a style guide recommendation which will also lead to it being inconsistently used among tutorials. I think this is one rule in which we'd be going against the grain.

Thoughts?

**Comment by rayfix** [comment]
The logic is sound.  

Tech editing pain aside, the fact is that most people do not use `final`. The new default is that a class is closed outside the module with no annotation. With whole object optimization the compiler automatically "closes" classes or property/method when it is not explicitly annotated with the access modifier `open`.  So I think the privacy rules do kick into effect.

**Comment by JessyCatterwaul** [comment]
I do agree that most people aren't using `final`, but I don't think that underuse represents intention. While I don't think tech editors need to audit for whether `final` should have been used, when it was not, it adds useful, enforced documentation, and belongs in the style guide in order to urge more people to adopt that clarity.

Instead of the imperative wording that exists now…
> Mark classes `final` when inheritance is not intended.
…I suggest that we alter the wording to reflect the same suggestive tone as exists for [Access Control](https://github.com/raywenderlich/swift-style-guide/blob/swift3/README.markdown#access-control).
> Marking classes or members as `final` in tutorials can distract from the main topic and is not required.
Then, another sentence about why it's good, and an example of why `final` would be used on a member, instead of the an entire type.

**Comment by rayfix** [comment]
Thanks for the discussion.  I took your idea @JessyCatterwaul    I do, however, think it can be useful to apply final to entire types.   19d78711bab22c2620c75c18e6a7a444b9b7b14d
