### ISSUE TITLE
Spacing

### ISSUE THREAD

**Issue by scotteg** [raywenderlich/swift-style-guide#257]
I believe the style guide should be revised to include a single space before the `:` in type definitions, but continue to include a space only after the `:` in other use cases (instance declarations, dictionaries), e.g.,

```
class TestDatabase : Database {
  var data: [String: CGFloat] = ["A": 1.2, "B": 3.2]
}
```

This matches Apple's style.

**Comment by rayfix** [comment]
There are two styles used within Apple.  One is used by the Apple documentation group for books, sample code, and blog posts and the other used by the standard library team.  We have chosen the system used by the documentation group for its simplicity and brevity.  (The rules which the standard library are much more involved, which is why I am told the documentation group rejected them.)  

I don't expect the standard library to fall into line on this as it would cause too much diff noise without adding any additional clarity.  I think it will remain one of those peculiar artifacts of the language's evolutionary history.

**Comment by scotteg** [comment]
@rayfix Ah, thanks for clarifying. Now I just need an Xcode plugin that automatically toggles preference sets and reformats all the code 🤔
