### ISSUE TITLE
Use () -> Void for closures with no parameters that return nothing

### ISSUE THREAD

**Issue by rayfix** [raywenderlich/swift-style-guide#264]
This seems to be the standard these days.  () -> (), (Void) -> () are not preferred.

**Comment by ISosnovik** [comment]
`() -> Void` is prefered

**Comment by JessyCatterwaul** [comment]
I think this rule should follow from two other rules:
1. Use `()` instead of `Void` for closure inputs.*
2. Use `Void` instead of `()` for closure outputs.
Especially with Swift 3's enforcement of parentheses for inputs, I think this adds clarity.

*It's not quite enough to just say "don't use `Void`" for inputs, relying on Swift's compiler to enforce parentheses,  because (although I have no idea why you'd need it) you can have an empty tuple as a parameter, e.g.
```swift
let ƒ: ( (), Int ) -> Void = {_, int in}

let void: Void = ƒ((), 1)
ƒ(void, 2)
```
That's the way I'd want to see `ƒ` defined, not like this:
```swift
let ƒ: (Void, Int) -> Void = {_, int in}
```

**Comment by rcritz** [comment]
Added.
