### ISSUE TITLE
Logical AND: "&&" or "," in control flow

### ISSUE THREAD

**Issue by klop** [raywenderlich/swift-style-guide#266]
I'm struggling to find any mention of this -- forgive me if I'm wrong, but using "," is equivalent to "&&" in various control flow statements. e.g.

```
let x: Bool = ...
let y: Bool = ...

// Logical AND using ","
if x, y {
    // Do something
}

// Logical AND using "&&"
if x && y {
    // Do something
}
```

Assuming both of these short-circuit, there doesn't seem to be a difference beyond style. Is there a preferred/prevalent style?

**Comment by RobertGummesson** [comment]
A couple of differences:

This:
`if x && y || z`
is **_not_** the same as this:
`if x, y || z` 

Another difference is that `x, y` only works with `if`, `guard` and `while`. In other words, you can do this:
`let a = b && c`
but not this:
`let a = b, c`

As outlined in [SE-0099](https://github.com/apple/swift-evolution/blob/master/proposals/0099-conditionclauses.md), the purpose of the comma was to avoid situations like these: 
`if let y = optional where z == 2`
That makes little sense since `z` has nothing to do with `y`.

Having that said, I am personally guilty of using the comma even without optional unwrapping involved. ;)

**Comment by klop** [comment]
Thanks for the response, I hadn't considered precedence. Could it be worth mentioning this in the style guide?
