### ISSUE TITLE
Ternary operator

### ISSUE THREAD

**Issue by RobertGummesson** [raywenderlich/swift-style-guide#277]
I recently saw a developer pretty much do this:
`result = a > b ? x = c > d ? c : d : y`
and was going to point to the guideline for the better practice. Then I realized that the section about the ternary operator hasn't been carried across to the Swift guideline. Any particular reason for this? 

I think the section found in the Objective-C guideline is good with the exception of the parentheses around the condition, which makes less sense in Swift. What about adding it here too?

This is what it could look like for Swift:

## Ternary Operator

The Ternary operator, ?: , should only be used when it increases clarity or code neatness. A single condition is usually all that should be evaluated. Evaluating multiple conditions is usually more understandable as an if statement, or refactored into instance variables. In general, the best use of the ternary operator is during assignment of a variable and deciding which value to use.

**Preferred:**

```
let value = 5
result = (value != 0 ? x : y)

let isHorizontal = true
result = (isHorizontal ? x : y)
```

**Not Preferred:**

```
result = a > b ? x = c > d ? c : d : y
```

_**Edit:** Updated the examples to use parentheses in accordance of the [Parenthesis section](https://github.com/raywenderlich/swift-style-guide#parentheses), although I personally disagree that they add clarity, at least for these particular examples._

**Comment by designatednerd** [comment]
I am very strongly in favor of this suggestion. I've been coding for years now and still have an awful time parsing ternaries as I read them. 

Particularly since we have so many noobs to both Swift and coding in general, I think we should try to avoid them as much as possible, but use these or somewhat stricter guidelines when it comes to "when do I use a ternary vs. an `if`/`else`?  

We **should** encourage people to use swift's `??` (instead of the Elvis operator `?:` which is used in Obj-C) for "use this if it's not null, otherwise use backup". This is the one piece of ternary logic I think does increase clarity rather than just letting you do more crap on one line. 

_goes back to yelling at kids to get off my lawn_

**Comment by JessyCatterwaul** [comment]
Because debugging is line-based, and lining things up vertically adds readability, the way I'd format this exact statement in other languages whose assignment operator returns a value is:
```
result =
  a > b
  ? x = c > d
    ? c
    : d
  : y
```
I think we can't get `x = c > d` to compile in Swift, right? And if so, it's confusing and probably outside the scope of the problem to address. (The problem with that line is that both assigning and returning in one statement is confusing, hence Swift disallowing it.) So we'll need a Swift example, and one that demonstrates why breaking up the statement into multiple lines isn't preferable to an alternative.

I actually don't find it too useful to just base things off of a contrived example. Can we get some of our questionable code to try formatting this way?
```swift
1 == 1
? 2 == 2
  ? 3 == 3
    ? "1, 2, 3!"
    : "1, 2"
  : "1"
: ""
```
---
And on the subject of the nil-coalescing operator, the guideline I've used is, "Align the first potential non-nil result, and all following ??s."
```swift
let ohMys = (
  🦁: String?.none,
  🐯: String?.some("🐅"),
  🐻: String?.none
)

let 🐅 =
  ohMys.🦁
  ?? ohMys.🐯
  ?? ohMys.🐻
  ?? "🐩"
```

**Comment by RobertGummesson** [comment]
When the coding communities have their say, chained and nested uses of the ternary operator adds confusion and is often discouraged ([example](https://stackoverflow.com/questions/160218/to-ternary-or-not-to-ternary) and [example](https://softwareengineering.stackexchange.com/questions/28314/ternary-operator-considered-harmful)). I'm therefore guessing I won't be the only one here who found that 1,2,3 pyramid a bit confusing. 

But yes, you are right about the `x = c > d` bit. That was just copy pasted from the objective-c style guide. This is what it should have been:

**Not Preferred:**
```
result = a > b ? c > d ? c : d : y
```

**Comment by rcritz** [comment]
Added.
