### ISSUE TITLE
4-space indentation.

### ISSUE THREAD

**Issue by ShikiSuen** [raywenderlich/swift-style-guide#351]
This is not a request thread but a discussion thread.

I've seen that lots of coding styles implementing 2-space indentation.
To me, it completely ruined the readability for indentations if using real half-width coding fonts like this one:
https://github.com/be5invis/Iosevka

Any foods for thought from someone else?

**Comment by JRG-Developer** [comment]
The purpose of this style guide is for books, articles, etc written and used on RayWenderlich.com

Particularly in print, horizontal width is limited, and hence, we opted for 2-space indentation instead of 4, even though this goes against the default Xcode setup.

If you'd like, feel free to fork this repository and make tweaks for your own team's use! ;]

However, spacing requirements won't be changed for this style guide. :]

**Comment by ShikiSuen** [comment]
@JRG-Developer Thanks for clarification.
Now it is clear that it is the fault of those people who are misusing your style guide in wrong occasions.
