### ISSUE TITLE
Preferred type inference of static vars inside extensions

### ISSUE THREAD

**Issue by ObjectiveCesar** [raywenderlich/swift-style-guide#356]
Hi everyone,

in the chapter type inference (https://github.com/raywenderlich/swift-style-guide#type-inference) there are several examples on how to work with types. In general the guidelines say you should let the compiler do the work and rely on implicit type inference as much as possible. But how would you handle static vars in for example an extension of `UIColor`. Consider the following code:

```
struct MyClass {
  let thisIsRed: UIColor = .redColor
  let thisIsAlsoRed: = UIColor.redColor
}

private extension UIColor {
  static var redColor: UIColor { UIColor(named: "verySpecialRed")! } // Yes, I'm force unwrapping here, I'm very sure the color asset exists
}
```

Which one of the two ways of access the color inside the extension is the preferred way?

**Comment by JessyCatterwaul** [comment]
Ah! In that case, my recommendation is `UIColor.redColor`*, because otherwise, you need a colon. But I'm not sure it warrants a recommendation in this style guide; it's hardly a difference. 

\* Sort of. Type properties should generally return instances of themselves, so a `Color` suffix is bad style. https://developer.apple.com/documentation/uikit/uicolor/1621924-red

**Comment by ObjectiveCesar** [comment]
Again thank you for answering!

Yeah, it’s hardly a difference but as “use type inference where possible” kind of is a guideline, I tend to also prefer `let myColor = UIColor.red`. 

And you are absolutely right: `UIColor.redColor` would be bad style. It is a bad example. Let’s call it `UIColor.specialRed` then. 😉
