### ISSUE TITLE
Title case usage for let values

### ISSUE THREAD

**Issue by aclissold** [raywenderlich/swift-style-guide#74]
``` swift
let MaximumWidgetCount = 100
```

I hate to say it, but I vehemently believe that TitleCase should be used strictly for names of types, and never for instances of types.

It's a difficult thing to get used to, coming from the worlds of `I_AM_REALLY_SURE_I_WANT_THIS_TO_BE_A_CONSTANT` of Java and `kIWantToSignifyThisIsAConstantButHateCaps` of Objective-C.

I'd argue that the ubiquity of "make it a `let` until proven otherwise" in Swift is very beneficial to readability as well as the compiler's ability to better optimize code (due to the increased frequency of immutable values), and that this ubiquity means that title case is not necessary, even for class-level constants.

:]

**Comment by Jessy-** [comment]
It's not called TitleCase; it's called PascalCase.

And it can't be used for constants. The logical reasoning would be:
1. Swift requires the name of the type to be used to call class methods (unlike C#, which only requires that outside of the class that defines the static method)
2. Swift allows class and instance methods to have the same signature
3. If you name a constant/variable the same as its defining type, you cannot differentiate between the class and instance methods.

However, you don't even need to bother going through that logic, because naming the constant the same as its type won't even compile. Ergo, camelCase for all fields. I can see why this would be confusing, because Apple got the casing wrong for enum constants. Those should also be camelCase.

**Comment by gregheo** [comment]
It's a clarity issue for me. Something that's a global- or module-level constant is important enough that I'd like its scope to be obvious. I actually like the `kSomeConstant` naming with the `k` – partly since it's a lower-case `k` (and satisfies the "all constants and variables are camel cased" rule) and also since it makes the scope obvious.

For tutorials and teaching, I think issues of scope are often confusing – is this a property? Local variable? Global constant? I think the current guideline helps with that. We can usually tell properties from methods apart based on their names even though they're all camel case; I suspect we can tell class/type names apart from constant names too, even if we UpperCamelCase them both.

But – I think globals are uncommon enough in our tutorials that we can go either way here depending on consensus here. And also depending on the enum discussion in issue #79.

**Comment by Jessy-** [comment]
If the code is written in English, k doesn't make sense. k also came from an era where monitors didn't have the ability to have some text look different from other text, and IDEs and CSS didn't exist. I'd like lets to look different than vars, but naming isn't the right way to handle that anymore. There are only two letter cases, but an infinite variety of how that text can be styled.

**Comment by porglezomp** [comment]
I'm of the opinion that `SCREAMING_SNAKE_CASE` is the best for global constants, mostly because when you have a global constant it's generally be serving the purpose that a `#define` would in Objective-C.

**Comment by arctouch-ericchamberlain** [comment]
Most of our global constants are for shared singletons, like:
```
let sharedSomeService = SomeService()
```

We put other constants into classes, structs, or enums, depending on context.
```
struct Debug {
  static let isLoggedToConsole = true
}
```
Debug.isLoggedToConsole is easier to read and manage.

**Comment by gregheo** [comment]
OK, we'll go camel case. I added a small hedge with `private` thinking this is still for a module-level constant. For exported globals I still think we need *something* different like SCREAMING_SNAKE_CASE but we can discuss that later.
