### ISSUE TITLE
Appending to arrays

### ISSUE THREAD

**Issue by wsmurphy** [raywenderlich/swift-style-guide#81]
Is there a consensus on use of operators instead of methods when possible?
[The Swift Programming Language](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/CollectionTypes.html) shows that the addition operator ````+=```` can be used instead of the ````append```` method to add to an array.

Considering the preference for subscript syntax, should use of the ````+=```` be preferred to keep code concise?

**Comment by gregheo** [comment]
The catch here is that `+` and `+=` add arrays to arrays. So you do need to write `array += [oneElement]` with the square brackets. Maybe there's some unnecessary overhead in making a one-element array there too? I doubt it's significant but there's that too.

Other thoughts? I'm OK with `array.append()` but otherwise not sure how prescriptive we need to be about this point.

**Comment by ColinEberhardt** [comment]
I'd vote for `append` here, using `+= [foo]` seems like an unnecessarily convolution simply as a way to use a fancy new operator!

**Comment by cwagdev** [comment]
+1 for `append`

**Comment by designatednerd** [comment]
+1 for append as well - I think the overhead of instantiating a second array to do something which we have a method for in the standard library isn't worth it.

**Comment by wsmurphy** [comment]
Thanks for the responses. Looks like the agreement is to stick with append. It does make sense to avoid the extra work to create an array just to append it.
