### ISSUE TITLE
using id as class instance variable name

### ISSUE THREAD

**Issue by MobileMon** [raywenderlich/swift-style-guide#84]
Naturally some objects have a property called "id"

However in objective c I could never use this because its a keyword so I'd use "Id" or something

In swift, id is not reserved so we can use it. Do you think its safe to use? Or will it cause compatibility issues if I ever want to use the swift code in objective c?

**Comment by klundberg** [comment]
Id is actually a valid property name in objective c (and I assume a valid method or variable name too but I never tried that). It makes syntax highlighting get a little funky but that's it. If you want to use that in obj-c visible swift code there shouldn't be any problem I believe.

**Comment by MobileMon** [comment]
No i think you misread what i said. "id" is not valid in objective c, so i forced to use "Id". However in swift "id" is valid and I don't need to use "Id". What am asking is if this is OK?

**Comment by gregheo** [comment]
I think you answered your own question – if you need backwards compatibility, then don't do it. If you're 100% Swift and it works, then sure. I wouldn't do it personally since there's still a lot of Obj-C out there, including in the runtime.

It's not really a style guide question so I'm going to close this. Feel free to open a discussion on the forums (http://www.raywenderlich.com/forums/) if you like.
