### ISSUE TITLE
Order of writing  property specifiers

### ISSUE THREAD

**Issue by Igor-Palaguta** [raywenderlich/swift-style-guide#97]
What order of property specifiers is more preferable
`private dynamic`
`dynamic private `

I prefer to use following order
`private dynamic lazy`

**Comment by conradwt** [comment]
Yes, I agree that the scope specifiers should proceed other specifiers in declarations.

**Comment by rayfix** [comment]
The generated API view puts it in the order you suggest.  If you make a property static that goes in front before all of the other modifiers.  (It calls this `class` method which I think is a bug.)  I am going to include a section on access control and plan to mention that access control modifiers should be put in front of the property.  I don't think I will mandate an order otherwise as it would be too difficult to remember and not provide much value.
