### ISSUE TITLE
Placing properties

### ISSUE THREAD

**Issue by Igor-Palaguta** [raywenderlich/swift-style-guide#98]
We can have different set of properties
1) Outlets
2) private state
3) public state + delegate

Where in class implementation you place it?
1) before any method
2) before function they are used first
3) first should be declared public properties then private

Please share your vision

**Comment by gregheo** [comment]
I'd have to find a link, but this was discussed before at length – it might have been in our Objective-C style guide.

For tutorials, our instructions are usually just "add these properties" and since order inside the class doesn't matter we left it unspecified.

**Comment by jawwad** [comment]
This is a really good question that I've been struggling with myself, but I don't think there is really a clear way to do this. In general, for myself, I've tried to do public, then outlets then private. The "@IBOutlet private weak var outletName!" lines create somewhat of a visual separation between public and private properties for me which I think is nice. Other than that I think a guideline is difficult. Also, as @gregheo noted, for the RayWenderlich tutorials such a guideline would get in the way.

**Comment by gregheo** [comment]
I should note that these are good questions and things to bring up and I'm not closing the issue because I don't think it's worthwhile. But *this* style guide is meant as a reference for our writers specific to tutorial project style, and I need to keep it short and to-the-point.

Maybe we should start a general style guide too, with all of these best practices but that's a whole other question and project. ;]
